name: On Push
run-name: Perform Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: actions/setup-node@v3
        with:
          node-version: '14.16.0'
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Project Dependencies
        run: npm install
      - name: Build Project
        id: build
        run: npm run build
      - name: Test Project
        id: test
        if: steps.build.outcome == 'success'
        run: npm run test
      - id: git-add
        if: steps.test.outcome == 'success'
        run: git add .
      - id: git-commit
        if: steps.git-add.outcome == 'success'
        run: git commit -m "Build and Test Successful"
      - if: steps.git-commit.outcome == 'success'
        run: git push